name: Fuzz
on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR number'
        required: true
        type: string
      author:
        description: 'Author of the PR'
        required: true
      branch:
        description: 'Branch to fuzz'
        required: true
        type: string
      head_sha:
        description: 'SHA of the PR head'
        required: true
        type: string
      duration:
        description: 'Duration of fuzzing in seconds'
        required: true
        type: number
      instance:
        description: 'Number of instances to run fuzzing (in multiple of 10)'
        required: true
        type: number
permissions:
  id-token: write
  contents: read
jobs:
  CheckInfo:
    runs-on: ubuntu-latest
    outputs:
      pr_head: ${{ steps.check-author.outputs.pr_head }}
    steps:
      - name: Check PR head
        id: check-author
        run: |
          if git ls-remote --exit-code --heads https://github.com/${{ github.event.inputs.author }}/dafny.git ${{ github.event.inputs.branch }}; then
            echo "pr_head=${{github.event.inputs.author}}" >> "$GITHUB_OUTPUT"
          else
            if git ls-remote --exit-code --heads https://github.com/dafny-lang/dafny.git ${{ github.event.inputs.branch }}; then
              echo "pr_head=dafny-lang" >> "$GITHUB_OUTPUT"
            else
              echo "pr_head=invalid" >> "$GITHUB_OUTPUT"
            fi
          fi