name: Update AWS Lambda
on:
  push:
    branches:
      - main
    paths:
      - 'aws_lambda/*'
permissions:
  id-token: write
  contents: read
jobs:
  UpdateLambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Zip the code
        run: |
          zip -j issue_dafny_bug.zip aws_lambda/lambda_function.py
      - name: Update lambda function
        run: |
          aws lambda update-function-code --function-name issue_dafny_bug --zip-file fileb://issue_dafny_bug.zip
