name: Update Issue Open

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to update'
        required: true
        type: number
      issuer:
        description: 'User who opened the issue'
        required: true
        type: string
      commit:
        description: 'Latest commit ID'
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  UpdateIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue
        run: |
          echo "Updating issue ${{ github.event.inputs.issue_number }} opened by ${{ github.event.inputs.issuer }} with commit ${{ github.event.inputs.commit }}"