name: Update PR Close

on:
  workflow_dispatch:
    inputs:
      pr_head_ref:
        description: 'PR head to close'
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Remove folder in S3
        run: |
          aws s3 rm s3://compfuzzci/bugs/${{ github.event.inputs.pr_head_ref }} --recursive