name: Update Issue Open

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to update'
        required: true
        type: number
      issuer:
        description: 'User who opened the issue'
        required: true
        type: string
      commit:
        description: 'Latest commit ID'
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs: